### ISSUE TITLE
Track Souvenirs

### ISSUE THREAD

**Issue by WinterCS003** [WinterCS003/Project-2#1]
As a user, I want to be able to track the souvenirs purchased on my trips and the corresponding costs.

**Acceptance criteria**
- [x] Generate a report that shows which souvenirs were purchased and their quantity and price
- [x] Report is updated after all purchases
- [x] Report shows total amount spent on trip
- [x] Report is specific to the user

**Definition of done**
The user should be able to generate a report that shows if they have bought any souvenirs. If no souvenirs are bought then the report should say so. Otherwise, the report will show the quantity and price as well as the total amount spent for the souvenirs. Report should update after every purchase.

**Tasks**
- [x] Implement souvenirs class
- [x] Implement purchases function
- [x] Implement Souvenirs Bought Report function/window
- [x] Implement View (GUI) for report with above information

**Tests**
- [x] Clicking the “track souvenirs” button should show a report with all the information specified above.
- [x] If there are no souvenirs purchased then the report should say so.
- [x] Report should show souvenirs purchased from all of the trip
- [x] Report should automatically update after every purchase

Story points: 1
