### ISSUE TITLE
Display Stadiums with Grass

### ISSUE THREAD

**Issue by WinterCS003** [WinterCS003/Project-2#10]
As a user, I want to know which stadium have grass surface with first letter order

**Acceptance criteria**
- [x] Report the team name on the list that stadiums have grass surface in first letter order
- [x] Report number of stadium team have grass surface
- [x] Report the team name on the list that stadiums don’t have grass surface in first letter order

**Definition of done**
The user should click on the “Grass surface” Button. Then a window pops up showing which stadium has grass surface and shows they are team names in order and how many teams are there.

**Tasks**
- [x] Implement Stadium class
- [x] Implement StadiumContain Class
- [x] Implement ButtonGUI
- [x] Implement report GUI

**Tests**
- [x] clicking on the button should display the stadiums that only have grass surfaces.
- [x] If there is no stadium team found, report no stadium team found

Story point: 2
