### ISSUE TITLE
Stadium Open Date

### ISSUE THREAD

**Issue by WinterCS003** [WinterCS003/Project-2#11]
As a user, I want to know the opening date for all stadiums.

**Acceptance criteria**
- [x] Report stadiums opened date
- [x] Report opened date in chronological order
- [x] Report number of stadiums that is opening

**Definition of done**
The user should click on the “Opened date” Button. Then a window pops up showing every stadium opened day and they are in chronological order.

**Tasks**
- [x] Implement Stadium class
- [x] Implement StadiumContain Class
- [x] Implement ButtonGUI
- [x] Implement report GUI

**Tests**
- [x] Click on the button should display the stadium's opened timeline.

Story point: 2
