### ISSUE TITLE
Trip to MLS

### ISSUE THREAD

**Issue by DPJDevelops** [WinterCS003/Project-2#12]
As a user I want to know the shortest path starting at a stadium in CA to all Major League Stadiums. 

**Acceptance criteria**
- [x] Print number of stadiums visited.
- [x]  Print order the stadiums were visited.
- [x] Print total distance traveled.
- [x] Information is specified for Major League Stadiums
- [x] Path is the minimum distance

**Definition of done**

The user should be able to click on the “Plan Trip" to get all the discussed above reports for only Major League Stadiums. All information is printed in an easy to read format.

**Tasks**
- [x]  Implement Stadium class
- [x] Implement StadiumContain Class
- [x]  Implement ButtonGUI
- [x]  Implement report GUI

**Tests**
- [x] Clicking on a button should allow user to specify Major League Stadiums
- [x] Report with all above information is created
- [x] Information is all accurate - ie shortest path
- [x] View remains stable

Story points: 3

**Comment by ObeseWallets** [comment]
- [ ]
