### ISSUE TITLE
Trip to ALS

### ISSUE THREAD

**Issue by DPJDevelops** [WinterCS003/Project-2#15]
As a user I want to know the shortest path starting at a stadium in CA to all American League Stadiums. 

**Acceptance criteria**
- [x] Print number of stadiums visited.
- [x]  Print order the stadiums were visited.
- [x] Print total distance traveled.
- [x] Only AL Stadiums are printed
- [x] Path printed is the minimum distance

**Definition of done**

The user should be able to click on the “Plan Trip" to get all the discussed above reports. All information should be specified for American League stadiums.

**Tasks**
- [x]  Implement Stadium class
- [x] Implement StadiumContain Class
- [x] Implement find path algorithm
- [x]  Implement ButtonGUI
- [x]  Implement report GUI

**Tests**
- [x] User should be able to click on a button to get specifically American League Stadiums
- [x] All above information is printed and accurate
- [x] Path generated is the minimum path
- [x] View remains stable

Story points: 3
