### ISSUE TITLE
Trip to NLS

### ISSUE THREAD

**Issue by DPJDevelops** [WinterCS003/Project-2#16]
As a user. I want to know the shortest path starting at a stadium in CA to all National League Stadiums. 

**Acceptance criteria**
- [x] Print number of stadiums visited.
- [x]  Print order the stadiums were visited.
- [x] Print total distance traveled.
- [x] Only National League Stadiums are printed
- [x] The minimum distance is printed

**Definition of done**

The user should be able to click on the “Plan Trip" to get all the above requirements. Print number of stadiums visited, order the stadiums visited, total distance traveled in a new window table. Below it should be NLS stadiums and minimum distance traveled.

**Tasks**
- [x]  Implement Stadium class
- [x] Implement StadiumContain Class
- [x] Implement a find path function
- [x]  Implement ButtonGUI
- [x]  Implement report GUI

**Tests**
- [x] User can click on a button to print path
- [x] User can specify to plan only NL Stadiums
- [x] All above information is printed and is accurate
- [x] View remains stable

Story points: 3
