### ISSUE TITLE
Dream Vacation plan

### ISSUE THREAD

**Issue by DPJDevelops** [WinterCS003/Project-2#17]
As a user I want to plan my dream vacation to any Baseball Stadiums in the US.

**Acceptance criteria**
- [x] Print number of stadiums visited.
- [x]  Print order the stadiums were visited.
- [x] Print total distance traveled.
- [x] Path is the shortest path

**Definition of done**

The user should be able to click on the “Plan Trip" to get all the above reports. User should be able to specifically choose custom stadiums from a list of stadiums.

**Tasks**
- [x]  Implement Stadium class
- [x] Implement StadiumContain Class
- [x] Implement findPath algorithm
- [x]  Implement ButtonGUI
- [x]  Implement report GUI

**Tests**
- [x]  Clicking on the Plan Trip button should have all of above information
- [x] User can specify any of the stadiums in the program
- [x] The shortest path of the custom stadiums is printed

Story points: 3
