### ISSUE TITLE
Change Stadium Location

### ISSUE THREAD

**Issue by WinterCS003** [WinterCS003/Project-2#2]
As a user, I want to be able to modify stadium information if a team moves into a new stadium.

**Acceptance criteria**
- [x] User must have admin credentials to make changes
- [x] User can choose a specific stadium and update their location
- [x] Distance to stadium is properly updated
- [x] Changes are reflected in the GUI and are saved.

**Definition of done**
The user should be able to click on a stadium and choose to edit its information. Before being given edit permissions, the user should be prompted for credentials. If an invalid credential is given, then an error message is displayed. Otherwise, a new window is opened that allows the user to change the location of a stadium. Before saving changes, the user is prompted for confirmation. All changes are saved during executions.

**Tasks**
- [x] Implement Stadium class
- [x] Implement StadiumContainer class
- [x] Implement View (GUI) for stadium location edit

**Tests**
- [x] User can specify a specific stadium to edit
- [x] All edits are saved and reflected throughout program
- [x] A new window is shown that allows the user to change stadium location.

Story points: 3
