### ISSUE TITLE
Add Stadium

### ISSUE THREAD

**Issue by WinterCS003** [WinterCS003/Project-2#3]
As a user, I want to be able to add a new team and corresponding stadium if major league baseball decides to expand.

**Acceptance criteria**
- [x] User can click on a button to add stadium
- [x] User is required to validate credentials before making changes
- [x] User is prompted for all information regarding stadium: Stadium Name, Team Name, Street Address, City, State, Zip, Box Office #, Date Opened, Seating Capacity
- [x] Otherwise, a new stadium is added and changes are saved
- [x] Map is updated accordingly

**Definition of done**
The user should be able to click on an add stadium button. On click the user is prompted for admin credentials. If the proper credentials are given then the user is required to input the values as described above. Any conflict will result in error messages and changes not being saved. The map is updated accordingly.

**Tasks**
- [x] Implement Stadium class
- [x] Implement StadiumContainer class
- [x] Implement DisplayMap class
- [x] Implement View (GUI) for stadium edits

**Tests**
- [x] Clicking the add stadium button should prompt user for credentials
- [x] Proper credential validation takes place and only administrators can edit.
- [x] A new window should prompt user for stadium information
- [x] Changes are saved

Story points: 3
