### ISSUE TITLE
Access Stadium Info

### ISSUE THREAD

**Issue by WinterCS003** [WinterCS003/Project-2#4]
As a user, I want to be able to randomly access any baseball stadium and their information.

**Acceptance criteria**
- [x] User should be able to click on any stadium in a map for their information
- [x] All stadium information is shown in a report
- [x] User should be able to switch to different stadiums

**Definition of done**
The user should be able to specify a stadium by clicking on it from the map. On click a report of all information specific to that stadium is displayed to the user. The user should be able to switch to different stadiums and generate a similar report. The user should not be able to make any changes.

**Tasks**
- [x] Implement Stadium class
- [x] Implement StadiumContainer class
- [x] Implement DisplayMap class
- [x] Implement View (GUI) for stadium info

**Tests**
- [x] Clicking on a stadium prints the correct information
- [x] User should not be able to make any changes, view only
- [x] User can click on any of the stadiums

Story points: 2
