### ISSUE TITLE
Feature: Make Souvenirs Modifiable by Admins

### ISSUE THREAD

**Issue by n-cheung** [WinterCS003/Project-2#5]
As a user with admin privileges, I want to be able to modify the lists of souvenirs at each stadium and and the souvenirs themselves.

**Acceptance Criteria**
- [x] User is able to add/delete/change souvenirs from the list of souvenirs.
- [x] User is able to modify the name, description, and price of souvenirs.

**Definition of Done**
The user should be able to modify the souvenir list for any souvenir if they are an admin.  Selecting a button will list all the souvenirs and the user will be able to add/remove souvenirs to/from and modify already existing souvenirs.

**Tasks**
- [x] Implement function to add souvenir to a list
- [x] Implement function to delete souvenir from a list
- [x] Implement function to change a souvenir's name
- [x] Implement function to change a souvenir's description
- [x] Implement function to change a souvenir's price

**Tests**
- [x] Modifying a souvenir list should update it in the GUI correctly
- [x] Modifying a souvenir should update it in the GUI correctly

Story Points: 3
