### ISSUE TITLE
Feature: Print Out Distance Between Any Two Stadiums

### ISSUE THREAD

**Issue by n-cheung** [WinterCS003/Project-2#6]
As a user, I want to be able to determine the distance between any two stadiums on the map.

**Acceptance Criteria**
- [x] User is able to determine the distance between any two stadiums on the map.

**Definition of Done**
The user will be able to select two stadiums on the map and press a button to determine the distance between them, the shortest distance of flights to take.

**Tasks**
- [x] Implement function to select two different nodes on the map
- [x] Implement function to calculate the distance between two stadium
- [x] Implement feature into the GUI

**Tests**
- [x] Manually calculate distances and compare to resulting values

Story points: 1
