### ISSUE TITLE
Feature: Display the Map with Trip Highlighted

### ISSUE THREAD

**Issue by n-cheung** [WinterCS003/Project-2#7]
As a user, I want to be able to see the stadiums on a map in the GUI and see the path of the current trip highlighted.

**Acceptance Criteria**
- [x] The user is able to view the map of stadiums in the GUI
- [x] The user is able to see a highlighted path if there was one calculated

**Definition of Done**
The user will be able visually see the trip generated for them by the program.  The path of the trip would then be highlighted, with the stadiums numerically ordered.

**Tasks**
- [x] Implement map into GUI
- [x] Implement function that handles travel path updates
- [x] Implement function that highlights trip path

**Tests**
- [x] Use the program trip functions and see if all trips show correctly on the map, with nodes correctly numbered

Story Points: 5
