### ISSUE TITLE
Display Major League Stadiums in Alphabetical Order

### ISSUE THREAD

**Issue by WinterCS003** [WinterCS003/Project-2#8]
As a user. I want to know the major league stadium name in alphabetical order.

**Acceptance criteria**
- [x] Display the name on a list of the major league stadiums in alphabetical order.
- [x] Number of major league stadium

**Definition of done**

User can click the “alphabetical order” button on the GUI .Then a window pop up and show the stadiums in alphabetical order on the table in the window

**Tasks**
- [x] Implement Stadium class
- [x] Implement buttonGUI
- [x] Implement reportGUI

**Tests**
- [x] Click on button and show the list
- [x] All information is present an sorted

Story point: 3
