### ISSUE TITLE
Display Stadiums Sorted by Name

### ISSUE THREAD

**Issue by WinterCS003** [WinterCS003/Project-2#9]
As a user. I want to know the names of the teams in the first letter order of the major league stadiums, american league stadiums and national league stadiums.  

**Acceptance criteria**
- [x] Allow user to select between all stadiums, american league, and national league.
- [x] Report the team name on the list of the major league stadiums in the first letter order 
- [x] Report the team name on the list of the american league stadiums in the first letter order.
- [x] Report the team name on the list of the national league stadiums in the first letter order.
- [x] Number of major league stadium teams
- [x] Number of american league stadium teams
- [x] Number of national league stadium teams

**Definition of done**

Users can click the “MLS team name” , “ALS team name” or “NLS team name” buttons on the GUI .Then a window pops up and shows the major league stadium team name,american league stadiums or national league stadiums in first letter order and numbers of teams on the list in the window. It is related to which button users choose.

**Tasks**
- [x] Implement Stadium class
- [x] Implement list to hold stadiums
- [x] Implement buttonGUI

**Tests**
- [x] User specified data is all present and sorted
- [x] Can handle added stadiums

Story point: 3
